"""Generate docs/DATA_FILE_CATALOG.md: a Markdown index of every tracked data file.

Documentation and research data live in Markdown. Data tables are Markdown
files carrying the marker of markdown_data.py; the only data kept in another
format is JSON that programs load as configuration or fixtures. Both kinds are
listed here with a link, their shape, a short content sample and the Markdown
documents that discuss them. Run from anywhere inside the repository; only
tracked files are read.
"""
import argparse
import json
from pathlib import Path
import subprocess
import sys

sys.path.insert(0, str(Path(__file__).resolve().parent))
import markdown_data

ROOT = Path(__file__).resolve().parents[2]
OUTPUT = ROOT / 'docs' / 'DATA_FILE_CATALOG.md'
DATA_SUFFIXES = ('.tsv', '.csv', '.json')
# Tool and package configuration that is not project data.
EXCLUDED = ('package.json', 'tsconfig', 'components.json', '.vscode/', 'LICENSE', 'requirements')


def tracked(pattern):
    result = subprocess.run(['git', 'ls-files', pattern], cwd=ROOT, capture_output=True, text=True, check=True)
    return [line for line in result.stdout.splitlines() if line]


def clean(text, limit=110):
    text = ' '.join(text.replace('|', '/').split())
    return text if len(text) <= limit else text[:limit - 1] + '…'


def describe(path):
    """(kind, size text, sample) of one data file."""
    data = (ROOT / path).read_text(encoding='utf-8', errors='replace')
    lines = [line for line in data.splitlines() if line.strip()]
    if path.endswith('.md'):
        header, rows = markdown_data.read_table(ROOT / path)
        sample = rows[0][1] if rows and len(header) == 2 else ''
        return ('Markdown table', '%d rows, %d columns' % (len(rows), len(header)),
                sample or 'columns: ' + ', '.join(header))
    if path.endswith(('.tsv', '.csv')):
        separator = '\t' if path.endswith('.tsv') else ','
        columns = max((line.count(separator) + 1 for line in lines), default=0)
        first = lines[0].split(separator) if lines else []
        header = bool(first) and all(cell and not cell[0].isdigit() and ' ' not in cell.strip() for cell in first) \
            and len(first) > 2
        if header:
            return 'table with header', '%d rows, %d columns' % (len(lines) - 1, columns), 'columns: ' + ', '.join(first)
        sample = first[1] if len(first) > 1 else (first[0] if first else '')
        return 'address or key list', '%d rows, %d columns' % (len(lines), columns), sample
    if path.endswith('.json'):
        try:
            value = json.loads(data)
        except ValueError:
            return 'JSON', '%d lines' % len(lines), ''
        if isinstance(value, dict):
            return 'JSON object', '%d top-level keys' % len(value), 'keys: ' + ', '.join(list(value)[:8])
        return 'JSON array', '%d items' % len(value), ''
    return 'text list', '%d lines' % len(lines), lines[0] if lines else ''


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--check', action='store_true', help='Exit with status 1 when the catalog is out of date')
    args = parser.parse_args()
    documents = {path: (ROOT / path).read_text(encoding='utf-8') for path in tracked('*.md')
                 if Path(path) != OUTPUT.relative_to(ROOT)}
    files = sorted(path for suffix in DATA_SUFFIXES for path in tracked('*' + suffix)
                   if not any(mark in path for mark in EXCLUDED))
    tables = sorted(path for path, text in documents.items() if markdown_data.MARKER in text)
    for path in tables:
        del documents[path]            # a data table is listed, not counted as an explaining document
    files = sorted(files + tables)
    groups = {}
    for path in files:
        groups.setdefault(str(Path(path).parent).replace('\\', '/'), []).append(path)
    unreferenced = []
    lines = ['# Data file catalog', '',
             'Generated by `runtime/research/build-data-file-catalog.py`; do not edit by hand. Regenerate after',
             'adding, removing or renaming a data file.', '',
             'Project documentation and research data are written in Markdown. A *Markdown table* below is a',
             'data file: one table that tools parse with `runtime/research/markdown_data.py` (print one column',
             'with `python runtime/research/markdown_data.py <file> [column]`). Most are selections for an',
             'offline analysis stage, with a native address or key in the first column and the label recorded',
             'when it was chosen in the second. The remaining entries are JSON files that programs load as',
             'configuration or test fixtures and that therefore keep their format; they are linked here so a',
             'reader can start from Markdown and reach every data file.', '']
    for folder in sorted(groups):
        lines += ['## `%s`' % folder, '', '| File | Kind | Size | First entry or columns | Explained in |',
                  '| --- | --- | --- | --- | --- |']
        for path in groups[folder]:
            kind, size, sample = describe(path)
            name = Path(path).name
            mentions = sorted(document for document, text in documents.items() if name in text)
            if not mentions:
                unreferenced.append(path)
            links = ', '.join('[%s](../%s)' % (Path(document).name if document.count('/') else document, document)
                              for document in mentions[:4]) or '— (only this catalog)'
            if len(mentions) > 4:
                links += ' and %d more' % (len(mentions) - 4)
            lines.append('| [%s](../%s) | %s | %s | %s | %s |' % (name, path, kind, size, clean(sample), links))
        lines.append('')
    lines += ['## Files no other document mentions', '']
    lines += ['- [%s](../%s)' % (Path(path).name, path) for path in unreferenced] or ['None.']
    lines += ['', 'Total: %d data files in %d folders; %d not mentioned outside this catalog.'
              % (len(files), len(groups), len(unreferenced)), '']
    text = '\n'.join(lines)
    if args.check:
        current = OUTPUT.read_text(encoding='utf-8') if OUTPUT.exists() else ''
        raise SystemExit(0 if current == text else 1)
    OUTPUT.write_text(text, encoding='utf-8', newline='\n')
    print(json.dumps({'files': len(files), 'folders': len(groups), 'unreferenced': len(unreferenced)}))


if __name__ == '__main__':
    main()
