"""Classify every entry of the game's product tables for recipe delivery.

Reads the converted product tables and the purchasable specials table of the
existing corpus, read-only, and applies the refusal rules of the product
domain (the same rules the research profile enforces on the running game's
own definitions, see runtime/native/asi/profile_180836/product_learn.h).
Writes one Markdown data table with the class of each entry.

Classes:
  catalogue_item          taught: craftable, listed by the catalogue under
                          crafting, trade, curiosities or cooking
  catalogue_technology    craftable and listed under technology
  catalogue_construction  craftable or a customisation part, listed under
                          construction (build parts)
  not_learnable           the game's own routine refuses it (not craftable and
                          not a customisation part)
  not_in_catalogue        learnable, but the game's catalogue does not list it
  blocked_repeatable      a repeatable purchase that must never become known
"""
import argparse
from pathlib import Path
import sqlite3
import sys
import xml.etree.ElementTree as ElementTree

sys.path.insert(0, str(Path(__file__).resolve().parent))
import markdown_data  # noqa: E402

SPECIALS = 'metadata/reality/tables/purchaseablespecials.mbin'
ITEM_CATEGORIES = ('Crafting', 'Trade', 'Curio', 'Cooking')


def classify(identifier, product_type, craftable, wiki, repeatable):
    if identifier in repeatable or identifier.startswith(('SPEC_FIREWORK', 'EXPD_FIREWORK')):
        return 'blocked_repeatable'
    if not craftable and product_type != 'CustomisationPart':
        return 'not_learnable'
    if wiki == 'NotEnabled':
        return 'not_in_catalogue'
    if wiki in ITEM_CATEGORIES:
        return 'catalogue_item'
    if wiki == 'Tech':
        return 'catalogue_technology'
    if wiki == 'Construction':
        return 'catalogue_construction'
    return 'not_in_catalogue'


def table_of(path):
    data = Path(path).read_bytes()
    if len(data) > 64 * 1024**2:
        raise SystemExit('Table byte budget exceeded')
    return next(node for node in ElementTree.fromstring(data).iter('Property') if node.get('name') == 'Table')


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--corpus', type=Path, required=True)
    parser.add_argument('--output', type=Path, required=True, help='Markdown data table to write')
    args = parser.parse_args()
    index = sqlite3.connect((args.corpus / 'index.sqlite').resolve().as_uri() + '?mode=ro', uri=True)
    rows = index.execute('SELECT xml_path FROM files WHERE path = ?', (SPECIALS,)).fetchall()
    if len(rows) != 1:
        parser.error('Expected exactly one purchasable specials source')
    repeatable = set()
    for entry in table_of(rows[0][0]):
        fields = {child.get('name'): child.get('value') for child in entry}
        if fields.get('IsConsumable') == 'true':
            repeatable.add(fields['ID'])
    out, counts, seen, sources = [], {}, set(), []
    for path, xml_path in index.execute(
            "SELECT path, xml_path FROM files WHERE path LIKE 'metadata/reality/tables/%' AND xml_path IS NOT NULL "
            "ORDER BY path"):
        with Path(xml_path).open('r', encoding='utf-8', errors='ignore') as handle:
            if 'template="cGcProductTable"' not in handle.read(400):
                continue
        sources.append('`%s`' % path)
        for entry in table_of(xml_path):
            fields = {child.get('name'): child for child in entry}
            identifier = fields['ID'].get('value')
            if identifier in seen:
                continue
            seen.add(identifier)
            product_type = list(fields['Type'])[0].get('value')
            craftable = fields['IsCraftable'].get('value') == 'true'
            nested = list(fields['WikiCategory'])
            wiki = nested[0].get('value') if nested else fields['WikiCategory'].get('value')
            result = classify(identifier, product_type, craftable, wiki, repeatable)
            counts[result] = counts.get(result, 0) + 1
            out.append([identifier, result, product_type, 'yes' if craftable else 'no', wiki,
                        str(len(list(fields['Requirements'])))])
    description = ('Class of every product for recipe delivery. Sources: %s. Generated by '
                   '`classify-product-delivery.py`; do not edit by hand. Counts: %s. Meaning of the classes and '
                   'the rules: [product delivery notes](../../docs/PRODUCT_DELIVERY_NOTES.md).'
                   % (', '.join(sources), ', '.join('%s %d' % item for item in sorted(counts.items()))))
    markdown_data.write_table(args.output, 'Product delivery classification', description,
                              ['ID', 'Class', 'Type', 'Craftable', 'WikiCategory', 'Ingredients'], out)
    print(counts)


if __name__ == '__main__':
    main()
