"""List the topics of the game's guide, as one Markdown data table.

Reads the converted guide table (metadata/reality/wiki), the reward table and the language files
of the existing corpus, read-only. The guide has categories, each with topics; a topic is either
open from the start or opened during play, and the game's reward GcRewardWikiTopic opens one by its
identifier. One row per topic: its identifier, its category, whether it is open from the start,
whether a reward of the game's own table names it, its title and its category's name in the 14
interface languages. The desktop application offers the topics that are not open from the start.
"""
import argparse
from pathlib import Path
import re
import sys
import xml.etree.ElementTree as ElementTree

sys.path.insert(0, str(Path(__file__).resolve().parent))
import markdown_data  # noqa: E402

GUIDE = 'metadata/reality/wiki.MXML'
REWARDS = 'metadata/reality/tables/rewardtable.MXML'
# Interface language and the name of the game's language files for it.
LANGUAGES = {'pt-BR': 'brazilianportuguese', 'pt-PT': 'portuguese', 'ja-JP': 'japanese', 'en-US': 'english',
             'fr-FR': 'french', 'it-IT': 'italian', 'de-DE': 'german', 'es-ES': 'spanish', 'nl-NL': 'dutch',
             'ko-KR': 'korean', 'pl-PL': 'polish', 'ru-RU': 'russian', 'zh-CN': 'simplifiedchinese',
             'zh-TW': 'traditionalchinese'}
ENTRY = re.compile(r'<Property name="Id" value="([^"]+)" />(.*?)</Property>', re.S)
VALUE = re.compile(r'<Property name="\w+" value="([^"]+)" />')
TOPIC = re.compile(r'<Property name="Topic" value="([^"]+)" />')


def field(node, name):
    return next(child for child in node if child.get('name') == name)


def strings(corpus, language, wanted):
    folder = next((corpus / 'archives').glob('NMSARC.MetadataEtc-*/language'))
    found = {}
    for path in sorted(folder.glob('nms_*_%s.MXML' % language)):
        for identifier, body in ENTRY.findall(path.read_text(encoding='utf-8')):
            if identifier in wanted and identifier not in found:
                value = VALUE.search(body)
                if value:
                    found[identifier] = (value.group(1).replace('&quot;', '"').replace('&apos;', "'")
                                         .replace('&amp;', '&').replace('|', '/').strip())
    return found


def source(corpus, name):
    found = sorted(corpus.glob('archives/*/' + name))
    if not found:
        raise SystemExit('missing ' + name)
    return found[0]


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--corpus', type=Path, required=True)
    parser.add_argument('--output', type=Path, required=True)
    args = parser.parse_args()
    rewarded = set(TOPIC.findall(source(args.corpus, REWARDS).read_text(encoding='utf-8')))
    topics = []
    for category in field(ElementTree.parse(source(args.corpus, GUIDE)).getroot(), 'Categories'):
        name = field(category, 'CategoryID').get('value')
        for topic in field(category, 'Topics'):
            topics.append((field(topic, 'TopicID').get('value'), name, field(topic, 'Unlocked').get('value')))
    wanted = {topic for topic, _, _ in topics} | {category for _, category, _ in topics}
    texts = {locale: strings(args.corpus, language, wanted) for locale, language in LANGUAGES.items()}
    for locale, found in texts.items():
        if wanted - set(found):
            raise SystemExit('%s lacks %s' % (locale, sorted(wanted - set(found))))
    rows = [[topic, category, 'yes' if unlocked == 'true' else 'no', 'yes' if topic in rewarded else 'no']
            + [texts[locale][topic].title() if texts[locale][topic].isupper() else texts[locale][topic]
               for locale in LANGUAGES]
            + [texts[locale][category] for locale in LANGUAGES]
            for topic, category, unlocked in topics]
    markdown_data.write_table(
        args.output, 'Guide topics',
        'The topics of the game\'s guide (`metadata/reality/wiki`): the topic, its category, whether it is open '
        'from the start (`Unlocked` in the table), whether a reward of the game\'s reward table names it '
        '(`GcRewardWikiTopic`), its title in the 14 interface languages and then its category\'s name in the '
        'same 14, from the game\'s language files. %d topics in %d categories; %d open from the start, %d named '
        'by a reward. Generated by `list-guide-topics.py`; do not edit by hand.'
        % (len(rows), len({row[1] for row in rows}), sum(1 for row in rows if row[2] == 'yes'),
           sum(1 for row in rows if row[3] == 'yes')),
        ['Topic', 'Category', 'Open', 'Rewarded'] + list(LANGUAGES) + ['Category ' + locale for locale in LANGUAGES],
        rows)
    print(len(rows), 'topics', sum(1 for row in rows if row[2] == 'no'), 'to offer')


if __name__ == '__main__':
    main()
