"""List the alien word groups of the game table, as one Markdown data table.

Reads the converted alien speech table of the existing corpus, read-only. A word of a race belongs
to a group named "<race prefix>_<suffix>"; the game's reward that teaches chosen words names groups
by that suffix together with a race, and one group may hold several words. One row per group: the
group as the save and the game name it, its race, the suffix the reward takes, the word
identifiers it teaches and its category. The desktop application lists these for a word request.
"""
import argparse
from pathlib import Path
import sys
import xml.etree.ElementTree as ElementTree

sys.path.insert(0, str(Path(__file__).resolve().parent))
import markdown_data  # noqa: E402

TABLE = 'metadata/reality/tables/nms_dialog_gcalienspeechtable.MXML'
# Prefix the game puts before a group for each race (handler of the specific-words reward, f35d30).
PREFIXES = {'Traders': 'TRA', 'Warriors': 'WAR', 'Explorers': 'EXP', 'Atlas': 'ATLAS', 'Builders': 'BUI'}


def field(node, *names):
    for name in names:
        node = next(child for child in node if child.get('name') == name)
    return node


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--corpus', type=Path, required=True)
    parser.add_argument('--output', type=Path, required=True)
    args = parser.parse_args()
    source = sorted(args.corpus.glob('archives/*/' + TABLE))
    if not source:
        raise SystemExit('missing ' + TABLE)
    groups, skipped = {}, 0
    for entry in field(ElementTree.parse(source[0]).getroot(), 'Table'):
        race = field(entry, 'Race', 'AlienRace').get('value')
        group = field(entry, 'Group').get('value')
        prefix = PREFIXES.get(race)
        if not prefix or not group.startswith(prefix + '_') or len(group) > 31:
            skipped += 1
            continue
        row = groups.setdefault(group, [group, race, group[len(prefix) + 1:], [],
                                        field(entry, 'Category', 'wordcategorytableEnum').get('value')])
        word = field(entry, 'Id').get('value')
        if word not in row[3]:
            row[3].append(word)
    rows = [[group, race, suffix, ' '.join(words), category] for group, race, suffix, words, category in groups.values()]
    counts = {race: sum(1 for row in rows if row[1] == race) for race in PREFIXES}
    markdown_data.write_table(
        args.output, 'Word delivery',
        'Every alien word group of the game table `nms_dialog_gcalienspeechtable`: the group, its race, the '
        'suffix the game\'s specific-words reward takes for it, the words it teaches and its category. '
        'Generated by `list-alien-words.py`; do not edit by hand. Groups per race: %s. Entries left out '
        '(a race without a prefix or a group that does not carry it): %d.'
        % (', '.join('%s %d' % item for item in counts.items()), skipped),
        ['Group', 'Race', 'Suffix', 'Words', 'Category'], rows)
    print(counts, 'skipped', skipped)


if __name__ == '__main__':
    main()
