"""List the game's season (expedition), Twitch and platform rewards as one Markdown data table.

Reads the three converted unlockable-reward tables and the purchasable specials
table of the existing corpus, read-only. Each row carries the reward ID, its
kind, the expedition number for season rewards, the product a Twitch or
platform reward maps to, and the table flags. The `Deliverable` column is `no`
for an ID that is also a repeatable (consumable) special, which must never be
marked known or redeemed; today there is none. The research signal script reads
this table to decide what a "redeem" request may carry.
"""
import argparse
import hashlib
from pathlib import Path
import sqlite3
import sys
import xml.etree.ElementTree as ElementTree

sys.path.insert(0, str(Path(__file__).resolve().parent))
import markdown_data  # noqa: E402

TABLES = {'season': 'metadata/reality/tables/unlockableseasonrewards.mbin',
          'twitch': 'metadata/reality/tables/unlockabletwitchrewards.mbin',
          'platform': 'metadata/reality/tables/unlockableplatformrewards.mbin'}
SPECIALS = 'metadata/reality/tables/purchaseablespecials.mbin'


def load(index, path):
    rows = index.execute('SELECT xml_path FROM files WHERE path = ?', (path,)).fetchall()
    if len(rows) != 1:
        raise SystemExit('Expected exactly one source for ' + path)
    data = Path(rows[0][0]).read_bytes()
    if len(data) > 32 * 1024**2:
        raise SystemExit('Byte budget exceeded for ' + path)
    return data


def entries(data):
    root = ElementTree.fromstring(data)
    table = next(node for node in root.iter('Property') if node.get('name') == 'Table')
    for entry in table:
        yield {child.get('name'): child for child in entry}


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--corpus', type=Path, required=True)
    parser.add_argument('--output', type=Path, required=True, help='Markdown data table to write')
    args = parser.parse_args()
    index = sqlite3.connect((args.corpus / 'index.sqlite').resolve().as_uri() + '?mode=ro', uri=True)
    consumable = {fields['ID'].get('value') for fields in entries(load(index, SPECIALS))
                  if fields['IsConsumable'].get('value') == 'true'}
    rows, hashes, counts = [], [], {}
    for kind, path in TABLES.items():
        data = load(index, path)
        hashes.append('%s `%s`' % (kind, hashlib.sha256(data).hexdigest()[:16]))
        for fields in entries(data):
            if kind == 'season':
                identifier = fields['ID'].get('value')
                seasons = [node.get('value') for node in fields['SeasonIds'] if node.get('value')]
                detail = ' '.join(seasons)
                flags = ' '.join(name for name in ('MustBeUnlocked', 'SwitchExclusive', 'UniqueInventoryItem')
                                 if fields[name].get('value') == 'true')
                product = identifier
            elif kind == 'twitch':
                identifier, product, detail, flags = (fields['TwitchId'].get('value'), fields['ProductId'].get('value'),
                                                      '', '')
            else:
                identifier, product, detail, flags = (fields['RewardId'].get('value'), fields['ProductId'].get('value'),
                                                      '', '')
            deliverable = 'no' if identifier in consumable or product in consumable else 'yes'
            rows.append([identifier, kind, detail, product, flags, deliverable])
            counts[kind] = counts.get(kind, 0) + 1
    description = ('Season (expedition), Twitch and platform rewards of the game tables. Sources: %s. Converted table '
                   'SHA-256 prefixes: %s. Generated by `list-unlockable-rewards.py`; do not edit by hand. Counts: %s. '
                   'Meaning and status: [reward redemption notes](../../docs/REWARD_REDEMPTION_NOTES.md).'
                   % (', '.join('`%s`' % path for path in TABLES.values()), ', '.join(hashes),
                      ', '.join('%s %d' % item for item in sorted(counts.items()))))
    markdown_data.write_table(args.output, 'Unlockable rewards', description,
                              ['ID', 'Kind', 'Expedition', 'Product', 'Flags', 'Deliverable'], rows)
    print(counts, 'not deliverable:', [row[0] for row in rows if row[5] == 'no'])


if __name__ == '__main__':
    main()
