"""List the refiner and cooking recipes and the fish of the game tables, as two Markdown data tables.

Reads the converted recipe table and fish table of the existing corpus, read-only. The desktop
application offers these entries one by one: a recipe request names recipe IDs, a fishing request
names fish (product) IDs. A fish that only a mission gives is listed as not deliverable, because
the bridge never records it.
"""
import argparse
from pathlib import Path
import sys
import xml.etree.ElementTree as ElementTree

sys.path.insert(0, str(Path(__file__).resolve().parent))
import markdown_data  # noqa: E402

RECIPES = 'metadata/reality/tables/nms_reality_gcrecipetable.MXML'
FISH = 'metadata/reality/tables/fishdatatable.MXML'


def table_of(corpus, path):
    source = sorted(corpus.glob('archives/*/' + path))
    if not source:
        raise SystemExit('missing ' + path)
    return ElementTree.parse(source[0]).getroot()


def field(node, *names):
    for name in names:
        node = next(child for child in node if child.get('name') == name)
    return node


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--corpus', type=Path, required=True)
    parser.add_argument('--recipes', type=Path, required=True)
    parser.add_argument('--fish', type=Path, required=True)
    args = parser.parse_args()

    rows = []
    for entry in field(table_of(args.corpus, RECIPES), 'Table'):
        result = field(entry, 'Result')
        kind = 'cooking' if field(entry, 'Cooking').get('value') == 'true' else 'refiner'
        domain = field(result, 'Type', 'InventoryType').get('value').lower()
        ingredients = ' '.join(field(item, 'Id').get('value') for item in field(entry, 'Ingredients'))
        rows.append([field(entry, 'Id').get('value'), kind, field(result, 'Id').get('value'), domain, ingredients])
    counts = {kind: sum(1 for row in rows if row[1] == kind) for kind in ('cooking', 'refiner')}
    markdown_data.write_table(
        args.recipes, 'Recipe delivery',
        'Every refiner and cooking recipe of the game table `nms_reality_gcrecipetable`: its ID, whether it is a '
        'cooking or a refiner recipe, what it makes (ID and whether that is a product or a substance) and its '
        'ingredients. The application lists these for a recipe request with chosen IDs and names each by what it '
        'makes. Generated by `list-recipes-and-fish.py`; do not edit by hand. Counts: cooking %d, refiner %d.'
        % (counts['cooking'], counts['refiner']),
        ['ID', 'Kind', 'Result', 'Result type', 'Ingredients'], rows)

    fish = []
    for entry in field(table_of(args.corpus, FISH), 'Fish'):
        mission = field(entry, 'RequiresMissionActive').get('value')
        fish.append([field(entry, 'ProductID').get('value'), field(entry, 'Quality', 'ItemQuality').get('value'),
                     'no' if mission else 'yes'])
    markdown_data.write_table(
        args.fish, 'Fish delivery',
        'Every fish of the game table `fishdatatable`: its product ID, its quality and whether the fishing request '
        'may record it (`no` for a fish that only a mission gives; the bridge skips those). Generated by '
        '`list-recipes-and-fish.py`; do not edit by hand. Counts: %d fish, %d deliverable.'
        % (len(fish), sum(1 for row in fish if row[2] == 'yes')),
        ['ID', 'Quality', 'Deliverable'], fish)
    print(counts, len(fish), 'fish')


if __name__ == '__main__':
    main()
