"""List the names of the 256 galaxies in the 14 interface languages, as one Markdown data table.

The game names a galaxy with one routine (build 180836, RVA 135a2a0): the first five take a
language string each, the others a word of the procedural generator, seeded from the galaxy's
number, put into the language's format string (UI_GALAXY_FORMAT). The words come from a report
of emulate-name-generation.py (--kind galaxy, English, seeds 0 to ff), which runs the game's own
routine; this script only puts each word into the format of each language, read from the
converted language files of the corpus. One language's branch of the routine rewrites the word
(when the game's language number is 12); that rewriting is not reproduced here.
"""
import argparse
import json
from pathlib import Path
import re
import sys

sys.path.insert(0, str(Path(__file__).resolve().parent))
import markdown_data  # noqa: E402

# Interface language and the name of the game's language files for it.
LANGUAGES = {'pt-BR': 'brazilianportuguese', 'pt-PT': 'portuguese', 'ja-JP': 'japanese', 'en-US': 'english',
             'fr-FR': 'french', 'it-IT': 'italian', 'de-DE': 'german', 'es-ES': 'spanish', 'nl-NL': 'dutch',
             'ko-KR': 'korean', 'pl-PL': 'polish', 'ru-RU': 'russian', 'zh-CN': 'simplifiedchinese',
             'zh-TW': 'traditionalchinese'}
FIXED = ('MAIN_GALAXY', 'SECOND_GALAXY', 'THIRD_GALAXY', 'FOURTH_GALAXY', 'FIFTH_GALAXY')
FORMAT, PLACEHOLDER = 'UI_GALAXY_FORMAT', '%GALNAME%'


def strings(corpus, language, wanted):
    folder = next((corpus / 'archives').glob('NMSARC.MetadataEtc-*/language'))
    found = {}
    for path in sorted(folder.glob('nms_*_%s.MXML' % language)):
        text = path.read_text(encoding='utf-8')
        for identifier in wanted:
            if identifier in found:
                continue
            at = text.find('<Property name="Id" value="%s" />' % identifier)
            if at < 0:
                continue
            values = [v for v in re.findall(r'<Property name="\w+" value="([^"]*)" />',
                                            text[at:text.find('</Property>', at)])[1:] if v]
            if values:
                found[identifier] = values[0].replace('&quot;', '"').replace('&amp;', '&')
    missing = [identifier for identifier in wanted if identifier not in found]
    if missing:
        raise SystemExit('%s lacks %s' % (language, missing))
    return found


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--corpus', type=Path, required=True)
    parser.add_argument('--report', type=Path, required=True, help='English report of emulate-name-generation.py')
    parser.add_argument('--output', type=Path, required=True)
    args = parser.parse_args()
    report = json.loads(args.report.read_text(encoding='utf-8'))
    records = report['records']
    if report['language'] != 'english' or len(records) != 256 or report['errors']:
        raise SystemExit('Need the English report of all 256 galaxies without errors')
    english = strings(args.corpus, 'english', FIXED + (FORMAT,))
    before, after = english[FORMAT].split(PLACEHOLDER)
    words = []
    for index, record in enumerate(records):
        if int(record['seed'], 16) != index:
            raise SystemExit('Report is not in galaxy order')
        name = record['name']
        if index < len(FIXED):
            if name != english[FIXED[index]]:
                raise SystemExit('Fixed name %d differs from the language file' % index)
            words.append(None)
        else:
            if not (name.startswith(before) and name.endswith(after)):
                raise SystemExit('Name %d is not in the English format' % index)
            words.append(name[len(before):len(name) - len(after)])
    columns = {locale: strings(args.corpus, language, FIXED + (FORMAT,)) for locale, language in LANGUAGES.items()}
    rows = []
    for index, word in enumerate(words):
        rows.append([str(index + 1)] + [
            table[FIXED[index]] if word is None else table[FORMAT].replace(PLACEHOLDER, word)
            for table in columns.values()])
    markdown_data.write_table(
        args.output, 'Galaxy names',
        'The 256 galaxies of the game by number (1 is the first) with their names in the 14 interface languages. '
        'Galaxies 1 to 5 have a language string each; the others are a word made by the game\'s own name routine '
        '(build 180836, RVA `135a2a0`, run under emulation by `emulate-name-generation.py --kind galaxy`) put into '
        'each language\'s `UI_GALAXY_FORMAT`. Generated by `list-galaxy-names.py`; do not edit by hand. Not '
        'reproduced: the rewriting of the word that the routine does for one language of the game.',
        ['Number'] + list(LANGUAGES), rows)
    print(len(rows), 'galaxies;', rows[0][4], '|', rows[9][4], '|', rows[255][4])


if __name__ == '__main__':
    main()
