"""List the game's fossil products as one Markdown data table.

Reads the converted product tables of the existing corpus, read-only, and
keeps every product whose ID begins with FOS_: the individual bones (type
ExhibitBone) and the craftable fossil display pieces. The research signal
script reads this table to decide what a fossil request may carry.
"""
import argparse
from pathlib import Path
import sqlite3
import sys
import xml.etree.ElementTree as ElementTree

sys.path.insert(0, str(Path(__file__).resolve().parent))
import markdown_data  # noqa: E402


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--corpus', type=Path, required=True)
    parser.add_argument('--output', type=Path, required=True, help='Markdown data table to write')
    args = parser.parse_args()
    index = sqlite3.connect((args.corpus / 'index.sqlite').resolve().as_uri() + '?mode=ro', uri=True)
    rows, sources = [], []
    for path, xml_path in index.execute(
            "SELECT path, xml_path FROM files WHERE path LIKE 'metadata/reality/tables/%' AND xml_path IS NOT NULL "
            "ORDER BY path"):
        source = Path(xml_path)
        with source.open('r', encoding='utf-8', errors='ignore') as handle:
            if 'template="cGcProductTable"' not in handle.read(400):
                continue
        if source.stat().st_size > 64 * 1024**2:
            parser.error('Product table byte budget exceeded')
        table = next(node for node in ElementTree.fromstring(source.read_bytes()).iter('Property')
                     if node.get('name') == 'Table')
        found = 0
        for entry in table:
            fields = {child.get('name'): child for child in entry}
            identifier = fields['ID'].get('value')
            if not identifier.startswith('FOS_'):
                continue
            rows.append([identifier, list(fields['Type'])[0].get('value'),
                         'yes' if fields['IsCraftable'].get('value') == 'true' else 'no'])
            found += 1
        if found:
            sources.append('`%s` (%d)' % (path, found))
    bones = sum(1 for row in rows if row[1] == 'ExhibitBone')
    description = ('Fossil products of the game tables: %d individual bones (type ExhibitBone) and %d other fossil '
                   'products. Sources: %s. Generated by `list-fossil-products.py`; do not edit by hand. Meaning and '
                   'status: [reward redemption notes](../../docs/REWARD_REDEMPTION_NOTES.md).'
                   % (bones, len(rows) - bones, ', '.join(sources)))
    markdown_data.write_table(args.output, 'Fossil products', description, ['ID', 'Type', 'Craftable'], rows)
    print(len(rows), 'fossil products,', bones, 'bones')


if __name__ == '__main__':
    main()
